# Docker Compose for zaJedno MVP
# This file orchestrates frontend (Vite), backend (FastAPI), and logging-server services.

version: '3.9'

services:
  backend:
    build:
      context: ./services
      dockerfile: ../railway.Dockerfile
    container_name: za_backend
    env_file:
      - ./services/.env
    ports:
      - "8000:8000"
    volumes:
      - ./services:/app
    depends_on:
      - db
    restart: unless-stopped

  logging-server:
    build:
      context: ./logging-server
      dockerfile: ../e2b.Dockerfile
    container_name: za_logging_server
    ports:
      - "9000:9000"
    volumes:
      - ./logging-server:/app
      - ./logs:/logs
    restart: unless-stopped

  frontend:
    build:
      context: ./app
      dockerfile: ../e2b.Dockerfile
    container_name: za_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./app:/app
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: za_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: za_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
